import food1 from "../images/food1.jpg"
import food2 from "../images/food2.jpg"
import knifeburger from "../images/knifeburger.jpg"
import food3 from "../images/food3.jpg"
import food8 from "../images/food8.jpg"
import food7 from "../images/food7.jpg"
import food10 from "../images/food10.jpg"
